### ISSUE TITLE
ClassCastException on Otp Page

### ISSUE THREAD

**Issue by dondaldo** [payu-intrepos/payumoney-new-sample-app#15]
app is crashing in new version com.payumoney.sdkui:plug-n-play:1.1.0
`  java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to com.payumoney.sdkui.ui.widgets.OtpEditText
                                                                        at com.payumoney.sdkui.ui.utils.OtpEditTextWatcher.afterTextChanged(Unknown Source:116)
                                                                        at android.widget.TextView.sendAfterTextChanged(TextView.java:9380)
                                                                        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:11939)
                                                                        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1262)
                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:574)
                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
                                                                        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
                                                                        at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:131)
                                                                        at android.widget.TextView.doKeyDown(TextView.jav`

**Comment by Rahul-Hooda** [comment]
Hey @dondaldo , Can you share steps to replicate the same. Also share your support library versions.
