### ISSUE TITLE
No static method newRequestQueue

### ISSUE THREAD

**Issue by arvindy10** [payu-intrepos/payumoney-new-sample-app#35]
When I call  below line then app crash
PayUmoneyFlowManager.startPayUMoneyFlow(paymentParam, activity, R.style.AppTheme_default, true);

Currently i am Using 1.5.0 vesion
    implementation('com.payumoney.sdkui:plug-n-play:1.5.0')

ERROR :
(Landroid/content/Context;Lcom/android/volley/toolbox/BaseHttpStack;)Lcom/android/volley/RequestQueue; in class Lcom/android/volley/toolbox/Volley; or its super classes (declaration of 'com.android.volley.toolbox.Volley' appears in /data/app/com.livenutrifit-nXiSGllzU1yL3m4Ua1n-Pw==/base.apk)
at com.payumoney.graphics.helpers.NetworkManager.getRequestQueue(NetworkManager.java:104)
        at com.payumoney.graphics.helpers.NetworkManager.<init>(NetworkManager.java:75)
        at com.payumoney.graphics.helpers.NetworkManager.getInstance(NetworkManager.java:91)
        at com.payumoney.graphics.AssetDownloadManager.init(AssetDownloadManager.java:83)

**Comment by arvindy10** [comment]
There was library conflict in my code now it is fixed after exclude

**Comment by chintu6666** [comment]
How you solved ?

**Comment by YogeshJ241** [comment]
@Arvind Could you please share how you have solved this issue?
