### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by bhavinwebdesk** [payu-intrepos/payumoney-new-sample-app#52]
- After adding the card when the sdk redirects to SdkWebViewActivitynew, It gives error:

`W/System.err(27385): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.xxx/com.payumoney.core.SdkWebViewActivityNew}; have you declared this activity in your AndroidManifest.xml?
W/System.err(27385): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2112)
W/System.err(27385): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1757)
W/System.err(27385): 	at android.app.Activity.startActivityForResult(Activity.java:4803)
W/System.err(27385): 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
W/System.err(27385): 	at android.app.Activity.startActivityForResult(Activity.java:4743)
W/System.err(27385): 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
W/System.err(27385): 	at com.payumoney.core.presenter.MakePayment.OnPaymentDetailsReceivedFromPayuMoney(SourceFile:424)
W/System.err(27385): 	at com.payumoney.core.SdkSession$18.onSuccess(SourceFile:1189)
W/System.err(27385): 	at com.payumoney.core.SdkSession$12.run(SourceFile:615)
W/System.err(27385): 	at android.os.Handler.handleCallback(Handler.java:907)
W/System.err(27385): 	at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err(27385): 	at android.os.Looper.loop(Looper.java:216)
W/System.err(27385): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
W/System.err(27385): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(27385): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
W/System.err(27385): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
V/InputMethodManager(27385): Reporting focus gain, without startInput
D/HwAutofillHelper(27385): recordCurrentInfo:0
D/HwAutofillHelper(27385): inputType = 18
`

 - This issue was asked before but closed without any solution: [Issue 22](https://github.com/payu-intrepos/payumoney-new-sample-app/issues/22)

**Comment by Rahul-Hooda** [comment]
@bhavinwebdesk - Is it happening when Don't keep activities is turned on?
