### ISSUE TITLE
[Crashing] You must supply a layout_height attribute.

### ISSUE THREAD

**Issue by rathodbhavikkqc** [payu-intrepos/payumoney-new-sample-app#59]
We are using : (‘com.payumoney.sdkui:plug-n-play:1.6.0’){ exclude group: ‘com.android.volley’ }
Following documentation  : https://developer.payumoney.com/android/

But getting following error

```
android.view.InflateException: Binary XML file line #55 in com.afeias:layout/fragment_pay_umoney: Binary XML file line #125: You must supply a layout_height attribute.
    Caused by: java.lang.UnsupportedOperationException: Binary XML file line #125: You must supply a layout_height attribute.
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:831)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8009)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8206)
        at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:2023)
        at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1917)
        at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:89)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.payumoney.sdkui.ui.fragments.PayUMoneyFragment.onCreateView(SourceFile:255)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by rathodbhavikkqc** [comment]
@Rahul-Hooda Please guide us here

**Comment by Rahul-Hooda** [comment]
@rathodbhavikkqc - This SDK is no longer supported and maintained. Please switch to PayUCheckoutPro SDK for better UI, UX and actively developed.

Doc - https://payumobile.gitbook.io/sdk-integration/android/payucheckoutpro
Sample App - https://github.com/payu-intrepos/PayUCheckoutPro-Android

Please drop a mail to mobile.integration@payu.in for all your integration related queries.
